name: Danger after check 

on: 
  workflow_run:
    workflows: ["Check pull request"]
    types:
      - completed

jobs:
  danger:
    name: Check pull request
    runs-on: macOS-latest
    steps:
      - name: Set up and run Danger
        if: cancelled() != true # 中断されない限り、エラーでも実行
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 標準で利用できるトークンを利用
          JOB_STATUS: ${{ job.status }} # jobのステータスを Danger へ受け渡す
        run: |
          gem install ${{ steps.gem-info.outputs.packages }}
          danger --remove-previous-comments --fail-on-errors=true
